org: angara94dev
service: serverless-offline-issue

useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: 'dev'
  region: us-east-1
  profile: default
  environment:
  iam:
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/aws-sdk/**
    - '**/*.js.map'
custom:
  serverless-offline:
  webpack:    
    webpackConfig: './webpack.config.cjs'   
    packager: 'npm'    
    includeModules:      
      forceExclude:        
        - aws-sdk
plugins:
  # - serverless-webpack # comment out to use without webpack
  - serverless-offline

functions:
  ping:
    name: ${self:service}-${self:provider.stage}-ping
    # handler: src/ping/ping.router # comment out to use without webpack
    handler: dist/src/ping/ping.router # comment out to use with webpack
    timeout: 30
    events:
      - http:
          path: 'v0/ping'
          method: any
          cors:
            origins:
              - '*'  
            headers:
              - '*'  
resources: